[features]
seeds = true

[programs.localnet]
lazy_distributor = "1azyvMnX9ptJgr8y18mhAJFQSHfFGjyGtPQ4Lnn99kj"
helium_sub_daos = "hdaojPkgSD8bciDc1w2Z4kXFFibCXngJiw2GRpEL7Wf"
data_credits = "credacwrBVewZAgCwNgowCSMbCiepuesprUWPBeLTSg"
helium_entity_manager = "hemABtqNUst4MmqsVcuN217ZzBspENbGt9uueSe5jts"
circuit_breaker = "circcmKGcSE61r768bFtD1GkG3x6qfEE1GD2PgwA6C3"
treasury_management = "treaRzaa4b98D1NQMQdQXzBupbgWhyJ2e1pXhJzkTwU"
lazy_transactions = "1atNarMiQ8RMLkcTwqHHUESs2f4SB3uouPKFLbXcMwE"
helium_voter_stake_registry = "hvsrY9UBtHhYRvstM2BWCsni81kevfn7B2DEhYbGA1a"

[workspace]
members = [
  "programs/lazy-distributor", 
  "programs/data-credits",
  "programs/helium-sub-daos",
  "programs/helium-entity-manager",
  "programs/circuit-breaker",
  "programs/treasury-management",
  "programs/lazy-transactions",
  "programs/helium-voter-stake-registry",
]

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.test.json -t 1000000 tests/**/*.ts"
build-deps = "anchor run build-metadata && anchor run build-bubblegum && anchor run build-noop && anchor run build-account-compression &&"
build-metadata = "cd deps/metaplex-program-library/token-metadata/program && pwd && cargo build-bpf && cd ../../../../"
build-bubblegum = "pushd deps/metaplex-program-library && pwd && anchor build -p mpl_bubblegum && popd"
build-account-compression = "pushd deps/solana-program-library/account-compression/programs/account-compression && pwd && cargo build-bpf && popd"
build-noop = "pushd deps/solana-program-library/account-compression/programs/noop && pwd && cargo build-bpf && popd"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./deps/metaplex-program-library/token-metadata/target/deploy/mpl_token_metadata.so"

[[test.genesis]]
address = "BGUMAp9Gq7iTEuizy4pqaxsTyUCBK68MDfK752saRPUY"
program = "deps/metaplex-program-library/bubblegum/program/target/deploy/mpl_bubblegum.so"

[[test.genesis]]
address = "noopb9bkMVfRPU8AsbpTUg8AQkHtKwMYZiFUjNRtMmV"
program = "./deps/solana-program-library/account-compression/target/deploy/spl_noop.so"

[[test.genesis]]
address = "cmtDvXumGCrqC1Age74AVPhSRVXJMd8PJS91L8KbNCK"
program = "./deps/solana-program-library/account-compression/target/deploy/spl_account_compression.so"

[test.validator]
url = "https://api.mainnet-beta.solana.com"

# Pyth price oracle
[[test.validator.clone]]
address = "JBu1AL4obBcCMqKBBxhpWCNUt136ijcuMZLFvTP7iWdB"

# Switchboard program
[[test.validator.clone]]
address = "SW1TCH7qEPTdLsDHRgPuMQjbQxKdH2aBStViMFnt64f"


# Switchboard aggregator
[[test.validator.clone]]
address = "E3cqnoFvTeKKNsGmC8YitpMjo2E39hwfoyt2Aiem7dCb"

# Switchboard aggregator history
[[test.validator.clone]]
address = "GvDMxPzN1sCj7L26YDK2HnMRXEQmQ2aemov8YBtPS7vR"

# Switchboard aggregator
[[test.validator.clone]]
address = "Fi8vncGpNKbq62gPo56G4toCehWNy77GgqGkTaAF5Lkk"

# [[test.validator.clone]]
# address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

# [[test.validator.clone]]
# address = "BGUMAp9Gq7iTEuizy4pqaxsTyUCBK68MDfK752saRPUY"

# [[test.validator.clone]]
# address = "noopb9bkMVfRPU8AsbpTUg8AQkHtKwMYZiFUjNRtMmV"

# [[test.validator.clone]]
# address = "cmtDvXumGCrqC1Age74AVPhSRVXJMd8PJS91L8KbNCK"
