[features]
seeds = true

[programs.localnet]
lazy_distributor = "1azyvMnX9ptJgr8y18mhAJFQSHfFGjyGtPQ4Lnn99kj"
helium_sub_daos = "hdaojPkgSD8bciDc1w2Z4kXFFibCXngJiw2GRpEL7Wf"
data_credits = "credacwrBVewZAgCwNgowCSMbCiepuesprUWPBeLTSg"
helium_entity_manager = "hemABtqNUst4MmqsVcuN217ZzBspENbGt9uueSe5jts"
circuit_breaker = "circcmKGcSE61r768bFtD1GkG3x6qfEE1GD2PgwA6C3"
treasury_management = "treaRzaa4b98D1NQMQdQXzBupbgWhyJ2e1pXhJzkTwU"

[workspace]
members = [
  "programs/lazy-distributor", 
  "programs/data-credits",
  "programs/helium-sub-daos",
  "programs/helium-entity-manager",
  "programs/circuit-breaker",
  "programs/treasury-management",
]

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.test.json -t 1000000 tests/**/*.ts"
build-deps = "anchor run build-metadata"
build-metadata = "cd deps/metaplex-program-library/token-metadata/program && pwd && cargo build-bpf && cd ../../../../"
build-vsr = "pushd deps/helium-voter-stake-registry && pwd && anchor build && popd"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./deps/metaplex-program-library/token-metadata/target/deploy/mpl_token_metadata.so"

[[test.genesis]]
address = "vsrZ1Nfkxmt1hVaB7ftvcj7XpRoQ1YtCgPLajeaV6Uj"
program = "deps/helium-voter-stake-registry/target/deploy/voter_stake_registry.so"