[workspace]
members = [
  "programs/*"
]
exclude = [
  "deps/metaplex-program-library/bubblegum/program", 
  "deps/metaplex-program-library/token-metadata/program",
  "utils/migration-tx-executor",
  "utils/ledger-migration-cli"
]
