[package]
name = "migration-tx-executor"
version = "0.0.1"
edition = "2021"

[profile.release]
overflow-checks = true

[dependencies]
anchor-client = "0.26.0"
clap = { version = "4.0.32", features = ["derive"] }
solana-client = "1.14.11"
lazy-transactions = { path = "../../programs/lazy-transactions" }
postgres = "0.19.4"
serde_json = "1.0"
shellexpand = "2.1.0"
